version: '3.8'

services:
  shell:
    build:
      context: ./shell
      args:
        CATALOG_URL: http://localhost/catalog
        CART_URL: http://localhost/cart
        PROFILE_URL: http://localhost/profile
    ports:
      - "127.0.0.1:3000:80"

  mfe-catalog:
    build: ./mfe-catalog
    ports:
      - "127.0.0.1:3001:80"

  mfe-cart:
    build: ./mfe-cart
    ports:
      - "127.0.0.1:3002:80"

  mfe-profile:
    build: ./mfe-profile
    ports:
      - "127.0.0.1:3003:80"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - shell
      - mfe-catalog
      - mfe-cart
      - mfe-profile
