upstream shell_upstream      { server shell:80; }
upstream catalog_upstream    { server mfe-catalog:80; }
upstream cart_upstream       { server mfe-cart:80; }
upstream profile_upstream    { server mfe-profile:80; }

server {
    listen 80;

    location / {
        proxy_pass http://shell_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /catalog/ {
        proxy_pass http://catalog_upstream/;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }

    location /cart/ {
        proxy_pass http://cart_upstream/;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }

    location /profile/ {
        proxy_pass http://profile_upstream/;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }
}
